### ISSUE TITLE
[BUG] Can't log in to google play store

### ISSUE THREAD

**Issue by ipari** [universal5433/android_device_samsung_trelte-common#14]
On first launching of google play store, this message is shown instead of the google login page.

```
There was a problem communicating with google servers.
```

My device is the N916S and These are versions I'd tried.
- open_gapps-arm-10.0-nano-20220215
- open_gapps-arm-10.0-pico-20220215
- open_gapps-arm-10.0-pico-20220110

Except GApps, everything is work well.
Phone call, sms, wifi, camera, ...

**Comment by ghost** [comment]
@ipari try using BitGapps

**Comment by ananjaser1211** [comment]
Fixed as of 20221231 build, make sure to install latest bitGapps or OpenGapps packages for Android 11
