### ISSUE TITLE
[Feature] MicroG / Signature Spoofing Support

### ISSUE THREAD

**Issue by ananjaser1211** [universal5433/android_device_samsung_trelte-common#18]
**Describe the feature**
- Support for MicroG

**Smartphone (please complete this feature following information part if you want device specific):**
Model: All models

**Comment by ananjaser1211** [comment]
Support added via https://github.com/universal5433/android_device_samsung_trelte-common/commit/5615e805538c08b7227e107477a4e7adc6335142

**Comment by dead-mavis** [comment]
> **Describe the feature**
> - Support for MicroG
> 
> **Smartphone (please complete this feature following information part if you want device specific):**
> Model: All models
>
