### ISSUE TITLE
[BUG] Bluetooth Stuttering while the screen is turning off

### ISSUE THREAD

**Issue by SunatP** [universal5433/android_device_samsung_trelte-common#6]
**Describe the bug**
I using Samsung Gear IconX 2018, and FiiIO BTR5 while I listening the music over bluetooth it's work just fine, after the screen is turning off, the music starting to stutter, lag, and cut-off 

**To Reproduce**
1. Go to Quick Setting
2. Turning on the Bluetooth
3. The Bluetooth connected to the Bluetooth headphones
3. Play some music (YouTube, Spotify)
4. See error (Music delay after playing for 2-3 seconds, after screening off it's stuttering)

**Expected behavior**
The stutter and cut-off while playing the music over bluetooth's issues are gone

**Smartphone model:**
 - Galaxy Note 4 N910C

**Additional context**
- Issue is due to bluetooth (possibly?)
[log_All.log](https://github.com/universal5433/android_device_samsung_trelte-common/files/8239094/log_All.log)

**Comment by ananjaser1211** [comment]
Improved in https://github.com/universal5433/android_kernel_samsung_universal5433/commit/3fecb1569fa63752dad7d8fa5d447097b771b640 https://github.com/universal5433/android_kernel_samsung_universal5433/commit/54358a4ac93dad6268d9aec38943c1664e03c28c

reopen if emerges like before
